# Generated by Django 5.1.7 on 2025-04-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('actors', models.JSONField(default=list)),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('rating', models.FloatField()),
                ('poster_url', models.CharField(max_length=255)),
                ('trailer_url', models.CharField(max_length=255)),
                ('genres', models.ManyToManyField(related_name='movies', to='api.genre')),
            ],
        ),
    ]
